language: java
jdk:
  - openjdk7
os:
  - linux
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P travis
script:
  - mvn clean test cobertura:cobertura coveralls:report -B -P travis -DrepoToken=${COVERALLS_REPO_TOKEN}
